-- Barangay personnel, administration terms, assignments, and certificate signatories.
-- Safe to run more than once in the Supabase SQL Editor.
--
-- This supersedes the earlier purok_leader_details.sql design. Purok leaders
-- are personnel assignments linked to a purok instead of permanent columns on
-- the puroks table.

CREATE TABLE IF NOT EXISTS barangay_terms (
    term_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term_name character varying(160) NOT NULL UNIQUE,
    starts_on date,
    ends_on date,
    is_active boolean NOT NULL DEFAULT false,
    notes text,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT barangay_terms_date_order
        CHECK (ends_on IS NULL OR starts_on IS NULL OR ends_on >= starts_on)
);

CREATE UNIQUE INDEX IF NOT EXISTS barangay_terms_one_active_idx
    ON barangay_terms (is_active)
    WHERE is_active = true;

CREATE TABLE IF NOT EXISTS barangay_positions (
    position_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_code character varying(80) NOT NULL UNIQUE,
    position_name character varying(160) NOT NULL,
    position_group character varying(30) NOT NULL DEFAULT 'staff',
    default_honorific character varying(30),
    is_elected boolean NOT NULL DEFAULT false,
    is_signatory_eligible boolean NOT NULL DEFAULT false,
    requires_purok boolean NOT NULL DEFAULT false,
    sort_order smallint NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT barangay_positions_group_check
        CHECK (position_group IN ('elected', 'appointed', 'staff', 'purok'))
);

CREATE TABLE IF NOT EXISTS barangay_personnel (
    personnel_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name character varying(180) NOT NULL UNIQUE,
    honorific character varying(30),
    contact_number character varying(40),
    email character varying(180),
    photo_url text,
    signature_data text,
    notes text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS barangay_personnel_assignments (
    assignment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personnel_id integer NOT NULL
        REFERENCES barangay_personnel(personnel_id) ON DELETE RESTRICT,
    position_id integer NOT NULL
        REFERENCES barangay_positions(position_id) ON DELETE RESTRICT,
    term_id integer NOT NULL
        REFERENCES barangay_terms(term_id) ON DELETE RESTRICT,
    purok_id integer
        REFERENCES puroks(purok_id) ON DELETE RESTRICT,
    committee text,
    title_override character varying(160),
    display_order smallint NOT NULL DEFAULT 0,
    starts_on date,
    ends_on date,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT barangay_assignments_date_order
        CHECK (ends_on IS NULL OR starts_on IS NULL OR ends_on >= starts_on)
);

CREATE UNIQUE INDEX IF NOT EXISTS barangay_assignments_unique_roster_idx
    ON barangay_personnel_assignments (
        term_id,
        personnel_id,
        position_id,
        COALESCE(purok_id, 0)
    );

CREATE INDEX IF NOT EXISTS barangay_assignments_active_term_idx
    ON barangay_personnel_assignments (term_id, is_active, display_order);

CREATE INDEX IF NOT EXISTS barangay_assignments_position_idx
    ON barangay_personnel_assignments (position_id, is_active);

ALTER TABLE requests
    ADD COLUMN IF NOT EXISTS signatory_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE issued_certificates
    ADD COLUMN IF NOT EXISTS signatory_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb;

COMMENT ON COLUMN requests.signatory_snapshot IS
    'Exact officials selected when a requested certificate was printed.';

COMMENT ON COLUMN issued_certificates.signatory_snapshot IS
    'Exact officials selected when a walk-in certificate was issued.';

INSERT INTO barangay_terms (
    term_name,
    starts_on,
    ends_on,
    is_active,
    notes
)
VALUES (
    'Current East Tapinac Administration',
    NULL,
    NULL,
    NOT EXISTS (
        SELECT 1
        FROM barangay_terms
        WHERE is_active = true
    ),
    'Initial roster imported from the barangay personnel chart.'
)
ON CONFLICT (term_name) DO UPDATE
SET starts_on = COALESCE(barangay_terms.starts_on, EXCLUDED.starts_on),
    notes = COALESCE(barangay_terms.notes, EXCLUDED.notes);

INSERT INTO barangay_positions (
    position_code,
    position_name,
    position_group,
    default_honorific,
    is_elected,
    is_signatory_eligible,
    requires_purok,
    sort_order
)
VALUES
    ('punong_barangay', 'Punong Barangay', 'elected', 'Hon.', true, true, false, 10),
    ('barangay_kagawad', 'Barangay Kagawad', 'elected', 'Hon.', true, true, false, 20),
    ('sk_chairperson', 'SK Chairperson', 'elected', 'Hon.', true, false, false, 30),
    ('barangay_secretary', 'Barangay Secretary', 'appointed', 'Ms.', false, false, false, 40),
    ('barangay_treasurer', 'Barangay Treasurer', 'appointed', 'Ms.', false, false, false, 50),
    ('purok_leader', 'Purok Leader', 'purok', NULL, false, false, true, 60),
    ('administrative_officer', 'Administrative Officer', 'staff', NULL, false, false, false, 100),
    ('executive_assistant', 'Executive Assistant', 'staff', NULL, false, false, false, 110),
    ('administrative_assistant', 'Administrative Assistant', 'staff', NULL, false, false, false, 120),
    ('administrative_clerk', 'Administrative Clerk', 'staff', NULL, false, false, false, 130),
    ('inventory_clerk', 'Inventory Clerk', 'staff', NULL, false, false, false, 140),
    ('bhrao', 'BHRAO', 'staff', NULL, false, false, false, 150),
    ('vawc_desk_officer', 'VAWC Desk Officer', 'staff', NULL, false, false, false, 160),
    ('social_welfare_desk_officer', 'Social Welfare Desk Officer', 'staff', NULL, false, false, false, 170),
    ('warrant_officer', 'Warrant Officer', 'staff', NULL, false, false, false, 180),
    ('command_center_operator', 'Command Center Operator', 'staff', NULL, false, false, false, 190),
    ('barangay_mechanic', 'Barangay Mechanic', 'staff', NULL, false, false, false, 200),
    ('barangay_driver', 'Barangay Driver', 'staff', NULL, false, false, false, 210),
    ('utility_worker', 'Utility Worker', 'staff', NULL, false, false, false, 220),
    ('maintenance_worker', 'Maintenance Worker', 'staff', NULL, false, false, false, 230),
    ('barangay_hall_caretaker', 'Barangay Hall Caretaker', 'staff', NULL, false, false, false, 240),
    ('covered_court_caretaker', 'Covered Court Caretaker', 'staff', NULL, false, false, false, 250),
    ('street_sweeper', 'Street Sweeper', 'staff', NULL, false, false, false, 260),
    ('pwd_desk_officer', 'PWD Desk Officer', 'staff', NULL, false, false, false, 270),
    ('other_staff', 'Other Barangay Personnel', 'staff', NULL, false, false, false, 999)
ON CONFLICT (position_code) DO UPDATE
SET position_name = EXCLUDED.position_name,
    position_group = EXCLUDED.position_group,
    default_honorific = EXCLUDED.default_honorific,
    is_elected = EXCLUDED.is_elected,
    is_signatory_eligible = EXCLUDED.is_signatory_eligible,
    requires_purok = EXCLUDED.requires_purok,
    sort_order = EXCLUDED.sort_order,
    is_active = true;

INSERT INTO barangay_personnel (
    full_name,
    honorific,
    contact_number
)
VALUES
    ('Dante L. Hondo', 'Hon.', NULL),
    ('Jeanette E. Alagon', 'Ms.', NULL),
    ('Frances Maria C. Tanor', 'Ms.', NULL),
    ('Jojo D. De Leon', 'Hon.', NULL),
    ('Crisanta D. Daniel', 'Hon.', NULL),
    ('Andrea A. Austria', 'Hon.', NULL),
    ('Florencia S. Abad', 'Hon.', NULL),
    ('Abner V. Capistrano', 'Hon.', NULL),
    ('Ronaldo E. Montilla', 'Hon.', NULL),
    ('Jennifer E. Yap', 'Hon.', NULL),
    ('Heyzel Marie I. Cayatin', 'Hon.', NULL),
    ('Gina M. Alcantara', NULL, NULL),
    ('Amalia D. Minas', NULL, NULL),
    ('Martes Z. Vicente', NULL, NULL),
    ('Henry Aguas', NULL, NULL),
    ('Cenen Abercas', NULL, NULL),
    ('Alberaldo D. Padilla', NULL, NULL),
    ('Maricris P. Cristal', NULL, NULL),
    ('Mary Jane B. Osorio', NULL, NULL),
    ('Eduardo U. Cristal', NULL, NULL),
    ('Rafael D. Nilo', NULL, NULL),
    ('Allen Mark B. Dalicano', NULL, NULL),
    ('Marjorie A. Austria', NULL, NULL),
    ('Ricardo O. Vanta', NULL, NULL),
    ('Epifania A. Austria', NULL, NULL),
    ('Bernabe Manuel Ebalo III', NULL, NULL),
    ('Fernando O. Aguilar', NULL, NULL),
    ('Mely Rose L. Pinon', NULL, NULL),
    ('Victoriano B. Acidre Jr.', NULL, NULL),
    ('Alvinar R. Ageron', NULL, NULL),
    ('Febelyn D. Candelosas', NULL, NULL),
    ('Robert L. Sionzon', NULL, NULL),
    ('Venus B. Aquino', NULL, NULL),
    ('Erlyn M. Marzan', NULL, NULL),
    ('Alexander Miranda', NULL, '0912-197-1976'),
    ('Robin Estrada', NULL, '0981-519-3246'),
    ('Eduardo Mercado', NULL, '0920-273-9383'),
    ('Leopoldo Vigo, Jr.', NULL, '0930-733-4147'),
    ('Carling B. Alcazar', NULL, '0931-937-0189'),
    ('Eduard T. Cristal', NULL, '0936-426-6959'),
    ('Christopher I. Quiambao', NULL, '0938-803-4676'),
    ('Ruben D. Daniel', NULL, '0969-103-4792'),
    ('Danilo Bartolome', NULL, '0916-289-5063'),
    ('Ruben V. Blanco', NULL, '0907-552-8224'),
    ('Rudy Jacinto', NULL, '0918-750-6921')
ON CONFLICT (full_name) DO UPDATE
SET honorific = COALESCE(barangay_personnel.honorific, EXCLUDED.honorific),
    contact_number = COALESCE(
        barangay_personnel.contact_number,
        EXCLUDED.contact_number
    ),
    is_active = true,
    updated_at = now();

WITH roster(
    full_name,
    position_code,
    committee,
    display_order,
    purok_name
) AS (
    VALUES
        ('Dante L. Hondo', 'punong_barangay', NULL, 1, NULL),
        ('Jeanette E. Alagon', 'barangay_secretary', NULL, 2, NULL),
        ('Frances Maria C. Tanor', 'barangay_treasurer', NULL, 3, NULL),
        ('Jojo D. De Leon', 'barangay_kagawad', 'Public Works & Livelihood', 10, NULL),
        ('Crisanta D. Daniel', 'barangay_kagawad', 'Education', 11, NULL),
        ('Andrea A. Austria', 'barangay_kagawad', 'Social Services / Finance', 12, NULL),
        ('Florencia S. Abad', 'barangay_kagawad', 'Health / Nutrition / Grievance', 13, NULL),
        ('Abner V. Capistrano', 'barangay_kagawad', 'Peace & Order', 14, NULL),
        ('Ronaldo E. Montilla', 'barangay_kagawad', 'Environment / Waste Segregation', 15, NULL),
        ('Jennifer E. Yap', 'barangay_kagawad', 'Ways & Means / BDRRM / Tourism', 16, NULL),
        ('Heyzel Marie I. Cayatin', 'sk_chairperson', 'Youth & Sports', 17, NULL),
        ('Alberaldo D. Padilla', 'administrative_officer', NULL, 100, NULL),
        ('Rafael D. Nilo', 'executive_assistant', NULL, 101, NULL),
        ('Maricris P. Cristal', 'administrative_assistant', NULL, 102, NULL),
        ('Gina M. Alcantara', 'administrative_clerk', NULL, 103, NULL),
        ('Marjorie A. Austria', 'administrative_clerk', NULL, 104, NULL),
        ('Ricardo O. Vanta', 'administrative_clerk', NULL, 105, NULL),
        ('Febelyn D. Candelosas', 'inventory_clerk', NULL, 106, NULL),
        ('Amalia D. Minas', 'bhrao', NULL, 107, NULL),
        ('Martes Z. Vicente', 'vawc_desk_officer', NULL, 108, NULL),
        ('Mary Jane B. Osorio', 'social_welfare_desk_officer', NULL, 109, NULL),
        ('Eduardo U. Cristal', 'warrant_officer', NULL, 110, NULL),
        ('Allen Mark B. Dalicano', 'command_center_operator', NULL, 111, NULL),
        ('Henry Aguas', 'barangay_mechanic', NULL, 112, NULL),
        ('Cenen Abercas', 'barangay_driver', NULL, 113, NULL),
        ('Robert L. Sionzon', 'barangay_driver', NULL, 114, NULL),
        ('Epifania A. Austria', 'utility_worker', NULL, 115, NULL),
        ('Bernabe Manuel Ebalo III', 'maintenance_worker', NULL, 116, NULL),
        ('Fernando O. Aguilar', 'barangay_hall_caretaker', NULL, 117, NULL),
        ('Victoriano B. Acidre Jr.', 'covered_court_caretaker', NULL, 118, NULL),
        ('Venus B. Aquino', 'covered_court_caretaker', NULL, 119, NULL),
        ('Mely Rose L. Pinon', 'street_sweeper', NULL, 120, NULL),
        ('Alvinar R. Ageron', 'street_sweeper', NULL, 121, NULL),
        ('Erlyn M. Marzan', 'street_sweeper', NULL, 122, NULL),
        ('Alexander Miranda', 'purok_leader', NULL, 201, 'Purok 1'),
        ('Robin Estrada', 'purok_leader', NULL, 202, 'Purok 2'),
        ('Eduardo Mercado', 'purok_leader', NULL, 203, 'Purok 3'),
        ('Leopoldo Vigo, Jr.', 'purok_leader', NULL, 204, 'Purok 4'),
        ('Carling B. Alcazar', 'purok_leader', NULL, 205, 'Purok 5'),
        ('Eduard T. Cristal', 'purok_leader', NULL, 206, 'Purok 6'),
        ('Christopher I. Quiambao', 'purok_leader', NULL, 207, 'Purok 7'),
        ('Ruben D. Daniel', 'purok_leader', NULL, 208, 'Purok 8'),
        ('Danilo Bartolome', 'purok_leader', NULL, 209, 'Purok 9'),
        ('Ruben V. Blanco', 'purok_leader', NULL, 210, 'Purok 10'),
        ('Rudy Jacinto', 'purok_leader', NULL, 211, 'Purok 11')
),
resolved AS (
    SELECT
        person.personnel_id,
        position.position_id,
        term.term_id,
        purok.purok_id,
        roster.committee,
        roster.display_order
    FROM roster
    JOIN barangay_personnel person
      ON lower(person.full_name) = lower(roster.full_name)
    JOIN barangay_positions position
      ON position.position_code = roster.position_code
    JOIN barangay_terms term
      ON term.term_name = 'Current East Tapinac Administration'
    LEFT JOIN puroks purok
      ON roster.purok_name IS NOT NULL
     AND lower(trim(purok.name)) = lower(roster.purok_name)
)
INSERT INTO barangay_personnel_assignments (
    personnel_id,
    position_id,
    term_id,
    purok_id,
    committee,
    display_order,
    is_active
)
SELECT
    resolved.personnel_id,
    resolved.position_id,
    resolved.term_id,
    resolved.purok_id,
    resolved.committee,
    resolved.display_order,
    true
FROM resolved
ON CONFLICT DO NOTHING;

-- Verification: active roster, including seven regular Kagawads.
SELECT
    assignment.assignment_id,
    personnel.full_name,
    position.position_name,
    assignment.committee,
    purok.name AS purok_name,
    term.term_name
FROM barangay_personnel_assignments assignment
JOIN barangay_personnel personnel
  ON personnel.personnel_id = assignment.personnel_id
JOIN barangay_positions position
  ON position.position_id = assignment.position_id
JOIN barangay_terms term
  ON term.term_id = assignment.term_id
LEFT JOIN puroks purok
  ON purok.purok_id = assignment.purok_id
WHERE term.is_active = true
  AND assignment.is_active = true
ORDER BY position.sort_order, assignment.display_order, personnel.full_name;
