-- Request proof upload support for CertiFast.
-- Run this in the Supabase SQL Editor after the certificate template migrations.
-- Bucket used by the app: certifast-uploads

ALTER TABLE certificate_templates
    ADD COLUMN IF NOT EXISTS proof_requirements jsonb DEFAULT '[]'::jsonb;

CREATE TABLE IF NOT EXISTS request_attachments (
    request_attachment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id integer NOT NULL REFERENCES requests(request_id) ON DELETE CASCADE,
    resident_id integer REFERENCES residents(resident_id) ON DELETE SET NULL,
    proof_key text NOT NULL,
    label text NOT NULL,
    file_name text NOT NULL,
    file_path text NOT NULL,
    file_url text,
    mime_type text,
    file_size integer DEFAULT 0,
    uploaded_at timestamp without time zone DEFAULT now()
);

CREATE INDEX IF NOT EXISTS request_attachments_request_id_idx
    ON request_attachments (request_id);

CREATE INDEX IF NOT EXISTS request_attachments_resident_id_idx
    ON request_attachments (resident_id);

ALTER TABLE request_attachments ENABLE ROW LEVEL SECURITY;

-- The app reads/writes request_attachments through the Express server, not directly
-- from the browser. Keeping RLS enabled prevents accidental public API exposure.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'Residents upload own request proof files'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "Residents upload own request proof files"
      ON storage.objects
      FOR INSERT
      TO authenticated
      WITH CHECK (
        bucket_id = 'certifast-uploads'
        AND name LIKE ('request-proofs/' || auth.uid()::text || '/%')
      )
    $policy$;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'Residents read own request proof files'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "Residents read own request proof files"
      ON storage.objects
      FOR SELECT
      TO authenticated
      USING (
        bucket_id = 'certifast-uploads'
        AND name LIKE ('request-proofs/' || auth.uid()::text || '/%')
      )
    $policy$;
  END IF;
END $$;

-- Common proof requirement presets stored on the templates.
-- Resident IDs/basic residency are verified during account activation, so request proofs
-- should only be certificate-specific supporting documents.
UPDATE certificate_templates
SET proof_requirements = '[]'::jsonb
WHERE template_key IN (
    'doc1-barangay-clearance',
    'doc1-certificate-residency',
    'doc1-cohabitation'
);

UPDATE certificate_templates
SET proof_requirements = '[{"key":"request_letter","label":"Request letter or agency requirement document","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key IN (
    'doc1-household-angkas-pass',
    'doc1-lockdown-residency-certification',
    'doc1-simple-residency-loan',
    'doc2-residency-bank-record',
    'doc2-centenarian-living-veteran',
    'doc3-senior-alive-well'
);

UPDATE certificate_templates
SET proof_requirements = '[{"key":"travel_documents","label":"Travel, repatriation, or destination document","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key IN (
    'doc1-acceptance-letter-quarantine',
    'doc1-undertaking-quarantine'
);

UPDATE certificate_templates
SET proof_requirements = '[{"key":"school_documents","label":"School requirement, enrollment, or assessment document","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key = 'doc2-residency-school-requirement';

UPDATE certificate_templates
SET proof_requirements = '[{"key":"medical_documents","label":"Medical certificate, bill, or hospital document","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key IN (
    'doc1-indigency-medical',
    'doc1-endorsement-medical-assistance',
    'doc1-hearing-impairment-certification',
    'doc2-indigent-good-moral-medical',
    'doc3-indigency-medical-assistance'
);

UPDATE certificate_templates
SET proof_requirements = '[{"key":"medical_documents","label":"Medical certificate, bill, or hospital document","required":true,"accept":"image/*,.pdf"},{"key":"travel_documents","label":"Travel, repatriation, or destination document","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key = 'doc2-endorsement-hospital-return';

UPDATE certificate_templates
SET proof_requirements = '[{"key":"school_documents","label":"School requirement, enrollment, or assessment document","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key IN (
    'doc1-good-moral',
    'doc1-indigency-educational-assistance'
);

UPDATE certificate_templates
SET proof_requirements = '[{"key":"school_documents","label":"School requirement, enrollment, or assessment document","required":true,"accept":"image/*,.pdf"},{"key":"assistance_documents","label":"Assistance request, referral, or supporting document","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key = 'doc2-minor-athlete-financial-assistance';

UPDATE certificate_templates
SET proof_requirements = '[{"key":"school_documents","label":"School requirement, enrollment, or assessment document","required":true,"accept":"image/*,.pdf"},{"key":"employment_documents","label":"Employment, income, or job seeker document","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key = 'doc1-indigency-spes-leap';

UPDATE certificate_templates
SET proof_requirements = '[{"key":"business_documents","label":"Business registration, permit application, or authorization","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key IN (
    'doc1-work-permit-certification',
    'doc1-no-business',
    'doc1-telecom-nap-permit',
    'doc1-business-owner-bir-certification',
    'doc2-business-closure-court-records',
    'doc2-business-assessor-permit',
    'doc2-registered-business-bank',
    'doc2-lpg-house-to-house-permit',
    'doc3-road-damage-permit',
    'doc3-bmbe-business-certificate',
    'doc3-pandemic-business-non-operation',
    'doc3-business-closure',
    'doc3-renovation-non-operational-business',
    'doc3-business-new-endorsement'
);

UPDATE certificate_templates
SET proof_requirements = '[{"key":"business_renewal_documents","label":"Previous permit or business renewal document","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key IN (
    'doc1-business-renewal-endorsement',
    'doc3-business-renewal-travel',
    'doc3-business-renewal-store'
);

UPDATE certificate_templates
SET proof_requirements = '[{"key":"property_documents","label":"Property title, tax declaration, lease, or lot document","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key IN (
    'doc1-property-ownership',
    'doc1-family-home-property',
    'doc1-lot-occupancy'
);

UPDATE certificate_templates
SET proof_requirements = '[{"key":"birth_record","label":"Birth certificate, PSA record, or civil registry document","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key IN (
    'doc1-live-birth-endorsement',
    'doc2-parent-relationship-spes',
    'doc3-child-details-4ps',
    'doc3-minor-stepbrother-birth-record'
);

UPDATE certificate_templates
SET proof_requirements = '[{"key":"guardianship_documents","label":"Birth record, guardianship proof, or authorization document","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key IN (
    'doc1-guardianship',
    'doc2-guardian-psa-certification'
);

UPDATE certificate_templates
SET proof_requirements = '[{"key":"medical_documents","label":"Medical certificate, bill, or hospital document","required":true,"accept":"image/*,.pdf"},{"key":"guardianship_documents","label":"Birth record, guardianship proof, or authorization document","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key = 'doc2-indigency-guardian-medical';

UPDATE certificate_templates
SET proof_requirements = '[{"key":"guardianship_documents","label":"Birth record, guardianship proof, or authorization document","required":true,"accept":"image/*,.pdf"},{"key":"travel_documents","label":"Travel, repatriation, or destination document","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key = 'doc3-sole-guardian-travel-assistance';

UPDATE certificate_templates
SET proof_requirements = '[{"key":"death_certificate","label":"Death certificate or funeral document","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key IN (
    'doc1-burial-assistance',
    'doc2-funeral-covered-court-indigency'
);

UPDATE certificate_templates
SET proof_requirements = '[{"key":"death_certificate","label":"Death certificate or funeral document","required":true,"accept":"image/*,.pdf"},{"key":"legal_documents","label":"Legal document, court record, or agency request","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key = 'doc1-no-marriage-death-claim';

UPDATE certificate_templates
SET proof_requirements = '[{"key":"calamity_proof","label":"Photo, incident report, or damage proof","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key IN (
    'doc2-flooded-residence-certification',
    'doc3-fire-damage-certification',
    'doc3-flood-victim-financial-assistance',
    'doc3-flood-victim-calamity-loan'
);

UPDATE certificate_templates
SET proof_requirements = '[{"key":"employment_documents","label":"Employment, income, or job seeker document","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key IN (
    'doc1-extended-duty-shift',
    'doc1-first-time-jobseeker',
    'doc2-first-time-jobseeker-oath',
    'doc2-unemployment-spes-certification',
    'doc3-first-time-jobseeker-clearance',
    'doc3-low-income-purok-leader',
    'doc3-low-income-tricycle-driver'
);

UPDATE certificate_templates
SET proof_requirements = '[{"key":"travel_documents","label":"Travel, repatriation, or destination document","required":true,"accept":"image/*,.pdf"},{"key":"employment_documents","label":"Employment, income, or job seeker document","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key = 'doc3-repatriated-ofw-unemployment';

UPDATE certificate_templates
SET proof_requirements = '[{"key":"legal_documents","label":"Legal document, court record, or agency request","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key IN (
    'doc1-certificate-appearance',
    'doc1-detained-bail-certification',
    'doc1-marital-separation-certification',
    'doc1-solo-parent-certification',
    'doc2-general-legal-records',
    'doc3-non-resident-persons'
);

UPDATE certificate_templates
SET proof_requirements = '[{"key":"event_documents","label":"Event proposal, authorization, or organizer letter","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key IN (
    'doc1-endorsement-toda-courtesy-call',
    'doc2-organization-water-clearance',
    'doc3-mlbb-tournament-permit'
);

UPDATE certificate_templates
SET proof_requirements = '[{"key":"assistance_documents","label":"Assistance request, referral, or supporting document","required":true,"accept":"image/*,.pdf"}]'::jsonb
WHERE template_key IN (
    'doc1-endorsement-financial-assistance',
    'doc1-dswd-eligibility-certification',
    'doc1-indigency-sibling-assistance',
    'doc2-indigency-income-means',
    'doc3-blank-indigency-form'
);
