-- Allow staff to return certificate requests for resident correction, while
-- preserving the original request ID and recording each resubmission.

ALTER TABLE public.requests
    ADD COLUMN IF NOT EXISTS revision_count integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_resubmitted_at timestamp without time zone;

COMMENT ON COLUMN public.requests.revision_count IS
'Number of times a resident corrected and resubmitted this request.';

COMMENT ON COLUMN public.requests.last_resubmitted_at IS
'Most recent time a needs_correction request was returned to pending review.';

CREATE TABLE IF NOT EXISTS public.request_correction_history (
    correction_history_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id integer NOT NULL REFERENCES public.requests(request_id) ON DELETE CASCADE,
    revision_number integer NOT NULL DEFAULT 0,
    event_type text NOT NULL CHECK (
        event_type IN ('correction_requested', 'resident_resubmitted')
    ),
    message text,
    actor_type text NOT NULL CHECK (actor_type IN ('admin', 'resident')),
    actor_id integer,
    actor_name text,
    request_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp without time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS request_correction_history_request_id_idx
    ON public.request_correction_history (request_id, created_at);

COMMENT ON TABLE public.request_correction_history IS
'Append-only history of staff correction requests and resident resubmissions.';
